name: 🐞 Bug Report
description: Create a report to help us improve kube-burner
title: "[BUG] "
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    attributes:
      label: kube-burner version
      description: Output of `kube-burner version` command
      placeholder: "v1.x.x"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run kube-burner with config '...'
        2. Execute command '...'
        3. Observe error '...'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen
    validations:
      required: true
  - type: textarea
    attributes:
      label: kube-burner configuration
      description: |
        Please provide your kube-burner configuration file or relevant sections
        Tip: You can attach files by clicking this area to highlight it and then dragging files in
      render: yaml
    validations:
      required: false
  - type: textarea
    attributes:
      label: Screenshots or output
      description: |
        If applicable, add screenshots or kube-burner output to help explain your problem
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment Information
      description: |
        Please provide information about your environment
      value: |
        - **OS**: 
        - **Kubernetes version**: 
        - **kube-burner version**: 
        - **Installation method**: (binary, container, go install, etc.)
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here (logs, error messages, etc.)
    validations:
      required: false